version: '3'
services:
#  notification-service:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=default
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo:latest
    container_name: iron-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: iron-redis
    ports:
      - "6381:6379"