version: '3'
services:
#  notification-service:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=default
#    depends_on:
#      - mongodb

  redis:
    image: redis:latest
    container_name: iron-redis
    ports:
      - "6381:6379"