spring:
  datasource:
    url: jdbc:h2:mem:notification
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    data: classpath:data-alert.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6381