spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  sql:
    init:
      # schema-locations: classpath:sql/domain-schema.sql
      data-locations: classpath:data-alert.sql
      encoding: UTF-8
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
#      id:
#        new:
#          new_generator_mappings: true
    show-sql: true
    # generate-ddl: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE