spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  sql:
    init:
      # schema-locations: classpath:sql/domain-schema.sql
      data-locations: classpath:data-alert.sql
      encoding: UTF-8
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

external:
  slack:
    host: https://slack.com/api/chat.postMessage
    maxRequestsPerSecond: 10
    initialDelay: 1000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE